/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as PublicRouteImport } from './app/_public'
import { Route as PublicIndexRouteImport } from './app/_public/index'
import { Route as PublicServicesIndexRouteImport } from './app/_public/services/index'
import { Route as PublicLoginIndexRouteImport } from './app/_public/login/index'
import { Route as ApiAuthSplatRouteImport } from './app/api/auth/$'
import { Route as privateDashboardChatIndexRouteImport } from './app/(private)/dashboard/chat/index'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicServicesIndexRoute = PublicServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginIndexRoute = PublicLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => PublicRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const privateDashboardChatIndexRoute =
  privateDashboardChatIndexRouteImport.update({
    id: '/(private)/dashboard/chat/',
    path: '/dashboard/chat/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/login/': typeof PublicLoginIndexRoute
  '/services/': typeof PublicServicesIndexRoute
  '/dashboard/chat/': typeof privateDashboardChatIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/login': typeof PublicLoginIndexRoute
  '/services': typeof PublicServicesIndexRoute
  '/dashboard/chat': typeof privateDashboardChatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/_public/': typeof PublicIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_public/login/': typeof PublicLoginIndexRoute
  '/_public/services/': typeof PublicServicesIndexRoute
  '/(private)/dashboard/chat/': typeof privateDashboardChatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/auth/$' | '/login/' | '/services/' | '/dashboard/chat/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/auth/$' | '/login' | '/services' | '/dashboard/chat'
  id:
    | '__root__'
    | '/_public'
    | '/_public/'
    | '/api/auth/$'
    | '/_public/login/'
    | '/_public/services/'
    | '/(private)/dashboard/chat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  privateDashboardChatIndexRoute: typeof privateDashboardChatIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/services/': {
      id: '/_public/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof PublicServicesIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login/': {
      id: '/_public/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof PublicLoginIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/dashboard/chat/': {
      id: '/(private)/dashboard/chat/'
      path: '/dashboard/chat'
      fullPath: '/dashboard/chat/'
      preLoaderRoute: typeof privateDashboardChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PublicRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
  PublicLoginIndexRoute: typeof PublicLoginIndexRoute
  PublicServicesIndexRoute: typeof PublicServicesIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
  PublicLoginIndexRoute: PublicLoginIndexRoute,
  PublicServicesIndexRoute: PublicServicesIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  privateDashboardChatIndexRoute: privateDashboardChatIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
